import type { RepoIdentifier } from "@/lib/github";
import type { LaunchKitFile } from "@/lib/launch-kit";

interface GitHubApiSuccess<T> {
  ok: true;
  data: T;
}

interface GitHubApiFailure {
  ok: false;
  status: number;
  error: string;
}

type GitHubApiResult<T> = GitHubApiSuccess<T> | GitHubApiFailure;

interface GitHubRepoDetails {
  default_branch: string;
}

interface GitHubRefResponse {
  object: {
    sha: string;
  };
}

interface GitHubContentResponse {
  sha?: string;
}

interface GitHubPullRequestResponse {
  html_url: string;
  number: number;
}

export interface LaunchKitPullRequestResult {
  branchName: string;
  pullRequestUrl: string;
  pullRequestNumber: number;
  filesChanged: number;
}

const GITHUB_API_BASE = "https://api.github.com";

const buildHeaders = (token: string): HeadersInit => ({
  Accept: "application/vnd.github+json",
  "Content-Type": "application/json",
  "User-Agent": "launchpad-audit",
  Authorization: `Bearer ${token}`,
});

const encodePath = (path: string): string => {
  return path.split("/").map((segment) => encodeURIComponent(segment)).join("/");
};

const githubRequest = async <T>(
  path: string,
  token: string,
  init: RequestInit = {},
): Promise<GitHubApiResult<T>> => {
  try {
    const response = await fetch(`${GITHUB_API_BASE}${path}`, {
      ...init,
      headers: {
        ...buildHeaders(token),
        ...init.headers,
      },
      next: { revalidate: 0 },
    });

    if (!response.ok) {
      let message = "GitHub no pudo completar la operación.";

      try {
        const payload = (await response.json()) as { message?: string };
        message = payload.message || message;
      } catch {
        // Keep stable error shape when GitHub returns a non-JSON error.
      }

      return {
        ok: false,
        status: response.status,
        error: message,
      };
    }

    return {
      ok: true,
      data: (await response.json()) as T,
    };
  } catch {
    return {
      ok: false,
      status: 502,
      error: "Error de red al escribir en GitHub.",
    };
  }
};

const buildBranchName = (): string => {
  return `launchpad-audit/${Date.now()}`;
};

const getContentSha = async (
  identifier: RepoIdentifier,
  path: string,
  branchName: string,
  token: string,
): Promise<string | undefined> => {
  const response = await githubRequest<GitHubContentResponse>(
    `/repos/${encodeURIComponent(identifier.owner)}/${encodeURIComponent(identifier.repo)}/contents/${encodePath(path)}?ref=${encodeURIComponent(branchName)}`,
    token,
  );

  if (!response.ok) {
    return undefined;
  }

  return response.data.sha;
};

const upsertFile = async (
  identifier: RepoIdentifier,
  branchName: string,
  file: LaunchKitFile,
  token: string,
): Promise<GitHubApiResult<{ content?: GitHubContentResponse }>> => {
  const existingSha = await getContentSha(identifier, file.path, branchName, token);
  const body: Record<string, unknown> = {
    message: `Add ${file.path} from Launchpad Audit`,
    content: Buffer.from(file.content, "utf-8").toString("base64"),
    branch: branchName,
  };

  if (existingSha) {
    body.sha = existingSha;
  }

  return githubRequest(
    `/repos/${encodeURIComponent(identifier.owner)}/${encodeURIComponent(identifier.repo)}/contents/${encodePath(file.path)}`,
    token,
    {
      method: "PUT",
      body: JSON.stringify(body),
    },
  );
};

const buildPullRequestBody = (files: LaunchKitFile[]): string => {
  const fileList = files.map((file) => `- \`${file.path}\`: ${file.description}`).join("\n");

  return `Generated by Launchpad Audit.

This PR adds a launch kit to improve repository onboarding, contribution flow, and public discoverability.

## Files

${fileList}

## Review Notes

- Review generated text before merging.
- Adjust install commands and project-specific details where needed.
- Keep or edit the templates based on your repository conventions.
`;
};

export const createLaunchKitPullRequest = async (
  identifier: RepoIdentifier,
  files: LaunchKitFile[],
  token: string,
): Promise<GitHubApiResult<LaunchKitPullRequestResult>> => {
  const repoResponse = await githubRequest<GitHubRepoDetails>(
    `/repos/${encodeURIComponent(identifier.owner)}/${encodeURIComponent(identifier.repo)}`,
    token,
  );

  if (!repoResponse.ok) {
    return repoResponse;
  }

  const defaultBranch = repoResponse.data.default_branch;
  const refResponse = await githubRequest<GitHubRefResponse>(
    `/repos/${encodeURIComponent(identifier.owner)}/${encodeURIComponent(identifier.repo)}/git/ref/heads/${encodePath(defaultBranch)}`,
    token,
  );

  if (!refResponse.ok) {
    return refResponse;
  }

  const branchName = buildBranchName();
  const createRefResponse = await githubRequest<GitHubRefResponse>(
    `/repos/${encodeURIComponent(identifier.owner)}/${encodeURIComponent(identifier.repo)}/git/refs`,
    token,
    {
      method: "POST",
      body: JSON.stringify({
        ref: `refs/heads/${branchName}`,
        sha: refResponse.data.object.sha,
      }),
    },
  );

  if (!createRefResponse.ok) {
    return createRefResponse;
  }

  for (const file of files) {
    const fileResponse = await upsertFile(identifier, branchName, file, token);

    if (!fileResponse.ok) {
      return fileResponse;
    }
  }

  const pullRequestResponse = await githubRequest<GitHubPullRequestResponse>(
    `/repos/${encodeURIComponent(identifier.owner)}/${encodeURIComponent(identifier.repo)}/pulls`,
    token,
    {
      method: "POST",
      body: JSON.stringify({
        title: "Add Launchpad Audit launch kit",
        head: branchName,
        base: defaultBranch,
        body: buildPullRequestBody(files),
      }),
    },
  );

  if (!pullRequestResponse.ok) {
    return pullRequestResponse;
  }

  return {
    ok: true,
    data: {
      branchName,
      pullRequestUrl: pullRequestResponse.data.html_url,
      pullRequestNumber: pullRequestResponse.data.number,
      filesChanged: files.length,
    },
  };
};
